### ISSUE TITLE
Hardcoded  ^HLT in regexp parsing for hltpath

### ISSUE THREAD

**Issue by simonepigazzini** [xiezhen/brilws#1]
Hi,

would it be possible to remove the hardcoded request that the --hltpath option only accept path starting with HLT? Calibration streams usually starts with AlCa so brilcalc returns an error when requesting info for such paths.

thanks,

simone

**Comment by xiezhen** [comment]
Hello,
   effective luminosity is intended for HLT_* path (physics) only, It is part of the design to filter OUT the AlCal*. 

Cheers,
Zhen
