### ISSUE TITLE
Could `brilcalc` support non-integer prescales?

### ISSUE THREAD

**Issue by missirol** [xiezhen/brilws#2]
After LS2, the prescales of Level-1 triggers can have non-integer values (as of now, with up to 2 digits after decimal point, meaning a given prescale value can be expressed as an integer divided by 100; for more info, see for example the [Level-1 uGT manual](https://raw.githubusercontent.com/cms-l1-globaltrigger/mp7_ugt_legacy/master/doc/mp7_ugt_firmware_specification/pdf/gt-mp7-firmware-specification.pdf)). This functionality has been used already during data-taking, one example being the HIon test run of 2022.

It looks like `brilcalc` currently does not support non-integer prescale values; an example is given in [*].

This appears consistent with the content of
https://github.com/xiezhen/brilws/blob/bfc1092a955327c66d31c8b905d8ab1b16c34cfc/brilws/dbschema/schema_trg.yaml#L40
https://github.com/xiezhen/brilws/blob/bfc1092a955327c66d31c8b905d8ab1b16c34cfc/brilws/dbschema/schema_trg.yaml#L50
(obviously, this is not necessarily all that needs to be updated.)

Could `brilcalc` be updated to support non-integer prescales?

[*]
Run-362319 (Fill-8413), LS 40
 - HLT = `HLT_HIZeroBias_v4` (HLT prescale = 1), L1T seed = `L1_ZeroBias` (L1T prescale = 2.7)
 - prescale-column index for LS=40: `5` ([prescale info from OMS](https://cmsoms.cern.ch/cms/triggers/prescale?cms_run=362319&cms_run_sequence=GLOBAL-RUN))

Output of `brilcalc` (notice `L1_ZeroBias/2` where `L1_ZeroBias/2.7` is expected):
```sh
> brilcalc --version
3.6.8
> brilcalc trg --prescale -r 362319 --hltpath "HLT_HIZeroBias_v*"
+--------+-------+----------+-------------+---------------------+-------+----------------+
| run    | cmsls | prescidx | totprescval | hltpath/prescval    | logic | l1bit/prescval |
+--------+-------+----------+-------------+---------------------+-------+----------------+
| 362319 | 1     | 5        | 2           | HLT_HIZeroBias_v4/1 | ONE   | L1_ZeroBias/2  |
| 362319 | 51    | 4        | 8           | HLT_HIZeroBias_v4/1 | ONE   | L1_ZeroBias/8  |
+--------+-------+----------+-------------+---------------------+-------+----------------+
```

**Comment by xiezhen** [comment]
Hello,
   Thanks for the alert. I have to first check if the corresponding type changes was implemented in the database view: CMS_UGT_MON.VIEW_UGT_RUN_PRESCALE . On which we have not been informed by any L1 UGT database contacts. BRIL side changes in database schema and software can only come later.  So the answer is yes but it'd take some time. 

Cheers,
Zhen

**Comment by missirol** [comment]
Hi @xiezhen , thanks for your feedback. Are there any news on this?

**Comment by xiezhen** [comment]
Hello,
   I confirm the L1 trigger schema is changed to float PRESCALE                   NOT NULL NUMBER(12,2) . We were not notified in 2022. The estimated changes include bril database schema change, database loading script change and client software change. The time estimation for this task , combined with HLT path definition change introduced in 2022, is mid-March 2023 at the worst case. 

Cheers,
Zhen

**Comment by missirol** [comment]
@xiezhen, okay, thanks. It would be great if you could keep us informed in this issue when there are updates.

**Comment by xiezhen** [comment]
Hello, yes,  we will update this ticket. I was informed that HLT prescale will remain integer which may or may not be a problem for this one.   These problem require similar development flow. I opened an issue 3 in this repo about HLT prescale.

**Comment by xiezhen** [comment]
@missirol Do you have the run number of first run  for the L1 prescale value to be a float? We have to decide from which point in time to reload data.

**Comment by missirol** [comment]
@xiezhen , I don't have that info. I can try to find out, but I think it'd be best to ask the L1T group.

**Comment by missirol** [comment]
I had a look. To my knowledge (which is not much), the first run with a fractional L1T prescale was [337636](https://cmsoms.cern.ch/cms/triggers/prescale?cms_run=337636&cms_run_sequence=GLOBAL-RUN) (see `L1_SingleMuCosmics_OMTF`). Let me repeat that it's better to ask the L1T group.

**Comment by xiezhen** [comment]
It is implemented and database tables changed.
see https://cms-talk.web.cern.ch/t/bril-worksuite-new-release-3-7-0/20099

**Comment by missirol** [comment]
Thank you @xiezhen ! Closing this issue.

```bash
> brilcalc --version
3.7.0

> brilcalc trg --prescale -r 362319 --hltpath "HLT_HIZeroBias_v*"
+--------+-------+----------+-------------+---------------------+-------+------------------+
| run    | cmsls | prescidx | totprescval | hltpath/prescval    | logic | l1bit/prescval   |
+--------+-------+----------+-------------+---------------------+-------+------------------+
| 362319 | 1     | 5        | 2.70        | HLT_HIZeroBias_v4/1 | ONE   | L1_ZeroBias/2.70 |
| 362319 | 51    | 4        | 8.00        | HLT_HIZeroBias_v4/1 | ONE   | L1_ZeroBias/8.00 |
+--------+-------+----------+-------------+---------------------+-------+------------------+
```
