### ISSUE TITLE
Add HLT_Physics paths to the bril calc lumi

### ISSUE THREAD

**Issue by sanuvarghese** [xiezhen/brilws#6]
Currently brilcalc does not recognize paths with no L1 seeds (eg : HLT_Physics_v , HLT_EphemeralPhysics_v ). This means we cannot calculate the effective luminosities of these paths.

To reproduce the issue ,

(in lxplus7 )

```
wget -O 2023D.json https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions23/Cert_Collisions2023_eraD_369803_370790_Golden.json

brilcalc lumi -u 1e33/cm2s -b "STABLE BEAMS" -i 2023D.json --hltpath HLT_EphemeralPh* > EHP_lumi.txt
```
It returns 

`no hltpath to l1bit mapping found`

Thanks,

Sanu 

cc @lathomas @missirol

**Comment by xiezhen** [comment]
[allhltpath.csv](https://github.com/xiezhen/brilws/files/15026333/allhltpath.csv)
Hello,
  this is correct: this path indeed does not exist. All hlt path currently in the bril summary database can be found in the attached csv file. As our data source  is the hltconfig db, please check with them.
The repository is moved to github cms-bril/brilws, please open a new ticket there if you have further problems.
thanks,
Zhen
